version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKER_URL: kafka:9092
      # CAMERA_DEVICE_INDEX: ${CAMERA_DEVICE_INDEX}
      CAMERA_WIDTH: ${CAMERA_WIDTH}
      CAMERA_HEIGHT: ${CAMERA_HEIGHT}

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
    environment:
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKER_URL: kafka:9092
