version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - zookeeper

  producer:
    build: ./backend/producer
    depends_on:
      - kafka
      - zookeeper

  consumer:
    build: ./backend/consumer
    depends_on:
      - kafka
      - zookeeper

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "frames:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
